import type { CirclesEventType } from '@circles-sdk/data'

export const EVENTS: CirclesEventType[] = [
	'CrcV1_HubTransfer',
	'CrcV1_Transfer',
	'CrcV1_Trust',
	'CrcV1_OrganizationSignup',
	'CrcV1_Signup',
	'CrcV2_ApprovalForAll',
	'CrcV2_CidV0',
	'CrcV2_CreateVault',
	'CrcV2_DepositDemurraged',
	'CrcV2_DepositInflationary',
	'CrcV2_Erc20WrapperDeployed',
	'CrcV2_Erc20WrapperTransfer',
	'CrcV2_GroupMintBatch',
	'CrcV2_GroupMintSingle',
	'CrcV2_GroupRedeem',
	'CrcV2_GroupRedeemCollateralBurn',
	'CrcV2_GroupRedeemCollateralReturn',
	'CrcV2_PersonalMint',
	'CrcV2_RegisterGroup',
	'CrcV2_RegisterHuman',
	'CrcV2_RegisterOrganization',
	'CrcV2_RegisterShortName',
	'CrcV2_Stopped',
	'CrcV2_StreamCompleted',
	'CrcV2_TransferBatch',
	'CrcV2_TransferSingle',
	'CrcV2_Trust',
	'CrcV2_UpdateMetadataDigest',
	'CrcV2_URI',
	'CrcV2_WithdrawDemurraged',
	'CrcV2_WithdrawInflationary'
]
