export const SECONDS_IN_MINUTE = 60
export const MINUTES_IN_HOUR = 60
export const HOURS_IN_DAY = 24
export const DAYS_IN_WEEK = 7
export const DAYS_IN_MONTH = 30
export const DAYS_IN_YEAR = 365
export const WEEKS_IN_YEAR = 52
export const MONTHS_IN_YEAR = 12

export const MILLISECONDS_IN_A_SECOND = 1000
export const MILLISECONDS_IN_A_MINUTE =
	MILLISECONDS_IN_A_SECOND * SECONDS_IN_MINUTE
export const MILLISECONDS_IN_AN_HOUR =
	MILLISECONDS_IN_A_MINUTE * MINUTES_IN_HOUR
export const MILLISECONDS_IN_A_DAY = MILLISECONDS_IN_AN_HOUR * HOURS_IN_DAY
export const MILLISECONDS_IN_A_MONTH = MILLISECONDS_IN_A_DAY * DAYS_IN_MONTH // Approximation
export const MILLISECONDS_IN_A_YEAR = MILLISECONDS_IN_A_DAY * DAYS_IN_YEAR // Approximation
